export * from './common';
export * from './sectores';
export * from './casos';
export * from './servicios';
export * from './about';
export * from './diagrama';
export * from './investigacion';
export * from './stack';
export * from './serviceLanding';
